config/routes.rb
MongoForms::Application.routes.draw do
  
  resources :extended_families
  root "extended_families#index"
end

app/models/extended_family.rb
class ExtendedFamily
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :relative
  field :alive, type: Mongoid::Boolean, default: true, pre_processed: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/extended_families_controller.rb
class ExtendedFamiliesController < ApplicationController
  before_action :set_extended_family, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /extended_families
  # GET /extended_families.json
  def index
    @extended_families = ExtendedFamily.all
  end

  # GET /extended_families/1
  # GET /extended_families/1.json
  def show
  end

  # GET /extended_families/new
  def new
    @extended_family = ExtendedFamily.new
    respond_with @extended_family
  end

  # GET /extended_families/1/edit
  def edit
  end

  # POST /extended_families
  # POST /extended_families.json
  def create
    @extended_family = ExtendedFamily.new(extended_family_params)
    @extended_family[:next_kin] = extended_family_params['relative']

    respond_to do |format|
      if @extended_family.save
        format.html { redirect_to @extended_family, notice: 'Extended family was successfully created.' }
        format.json { render action: 'show', status: :created, location: @extended_family }
        format.js { @extended_families = ExtendedFamily.all }
      else
        format.html { render action: 'new' }
        format.json { render json: @extended_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extended_families/1
  # PATCH/PUT /extended_families/1.json
  def update
    respond_to do |format|
      if @extended_family.update(extended_family_params)
        format.html { redirect_to @extended_family, notice: 'Extended family was successfully updated.' }
        format.json { head :no_content }
        format.js { @extended_families = ExtendedFamily.all }
      else
        format.html { render action: 'edit' }
        format.json { render json: @extended_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extended_families/1
  # DELETE /extended_families/1.json
  def destroy
    @extended_family.destroy
    respond_to do |format|
      format.html { redirect_to extended_families_url }
      format.json { head :no_content }
      format.js { @extended_families = ExtendedFamily.all }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extended_family
      @extended_family = ExtendedFamily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extended_family_params
      params.require(:extended_family).permit(:relative, :alive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extended_families_helper.rb
module ExtendedFamiliesHelper
end

app/views/extended_families/_extended_family.html.haml
%tr
  %td
    = link_to edit_extended_family_path(extended_family), remote: true do
      = fa_icon "edit"
  %td= extended_family.relative
  %td= extended_family.alive
  %td
    = link_to extended_family, method: :delete, data: { confirm: 'Are you sure?' }, class: :small_button, remote: true do
      = fa_icon "minus"

app/views/extended_families/_form.html.haml
= form_for @extended_family, remote: true do |f|
  - if @extended_family.errors.any?
    #error_explanation
      %h2= "#{pluralize(@extended_family.errors.count, "error")} prohibited this extended_family from being saved:"
      %ul
        - @extended_family.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    = f.label :relative
    = f.text_field :relative
    = f.label :alive
    = f.check_box :alive
    = button_tag type: :button, id: :cancel_button, class: :small_button do
      Cancel
    = f.submit 'Save', class: "small_button primary_button"

app/views/extended_families/_new_relative_link.html.haml
= link_to new_extended_family_path, remote: true, id: :new_family_member, class: "active_button small_button" do
  = fa_icon "plus"

app/views/extended_families/create.js.haml
:plain
  $('tbody#relatives').html("#{escape_javascript(render @extended_families)}");
  $('#new_relative_form').hide();
  $('#new_relative_link').show();

app/views/extended_families/destroy.js.haml
:plain
  $('tbody#relatives').html("#{escape_javascript(render @extended_families)}");

app/views/extended_families/edit.html.haml
%h1 Editing extended_family

= render 'form'

= link_to 'Show', @extended_family
\|
= link_to 'Back', extended_families_path

app/views/extended_families/edit.js.haml
:plain
  $('#new_relative_form').html("#{escape_javascript(render 'form')}");
  $('#new_relative_form').show();
  $('#new_relative_link').hide();

app/views/extended_families/index.html.haml
#navigation_menu
  #relatives_grouping
    = link_to_unless_current "My Family", "#", class: "pure-menu-heading" 
    %ul
      %li.pure-menu-selected= link_to_unless_current "Immediate Familty", "#"
      %li= link_to_unless_current "Home animals", "#"
      %li= link_to_unless_current "Distant relatives", "#"

#family_memebers_table
  %table
    %thead
      %tr
        %th
        %th Relative
        %th Alive
        %th
          #new_relative_link
            = render 'new_relative_link'
    %tbody#relatives
      = render @extended_families
#new_relative_form

app/views/extended_families/new.html.haml
%h1 New extended_family

= render 'form'

= link_to 'Back', extended_families_path

app/views/extended_families/new.js.haml
:plain
  $('#new_relative_form').html("#{escape_javascript(render 'form')}");
  $('#new_relative_form').show();
  $('#new_relative_link').hide();

app/views/extended_families/show.html.haml
%p#notice= notice

%p
  %b Relative:
  = @extended_family.relative
%p
  %b Alive:
  = @extended_family.alive

= link_to 'Edit', edit_extended_family_path(@extended_family)
\|
= link_to 'Back', extended_families_path

app/views/extended_families/update.js.haml
:plain
  $('tbody#relatives').html("#{escape_javascript(render @extended_families)}");
  $("#new_relative_form").hide();
  $("#new_relative_link").show();

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MongoForms
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield